### ISSUE TITLE
Is there an open-source dataset available on Call Center Segmentation? 

### ISSUE THREAD

**Issue by hamidomar** [alvaroarcelus/Sentiment-Analysis-Pipeline-for-Call-Center-Calls#1]

**Comment by alvaroarcelus** [comment]
Hi @hamidomar !
Sorry for the late reply. 
There is not an open source data-set but it should work if you add your own voice recordings in Spanish into the directory `/recordings` .

Given the late response, I imagine you've solved the issue by now. 
Please let me know if you have further questions :)
